module.exports = Object.freeze({
    ACTIVE: 'ACTIVE',
    BLOCK: 'BLOCK',
    DELETE: 'DELETE',
    CANCEL: 'CANCEL',
    SUSPENDED: 'SUSPENDED',
    EXPIRED: 'EXPIRED',
    REQUESTPENDING:'REQUESTPENDING',
    PENDING:'PENDING'
})