
module.exports = Object.freeze({
    BANK_STATEMENT_REQUIRED: 'BANK_STATEMENT_REQUIRED',
    EXTRA_KYC_REQUIRED: 'EXTRA_KYC_REQUIRED',
    NO_ADDITIONAL_VERIFICATION_NEEDED: 'NO_ADDITIONAL_VERIFICATION_NEEDED',
    NO_PAYMENT_RECEIPT_NEEDED: 'NO_PAYMENT_RECEIPT_NEEDED',
    PAN_REQUIRED: 'PAN_REQUIRED',
    PAYMENT_RECEIPT_REQUIRED: 'PAYMENT_RECEIPT_REQUIRED',
    PAYMENT_GATEWAY_PAYOUT: 'PAYMENT_GATEWAY_PAYOUT',
    PHOTO_ID_REQUIRED: 'PHOTO_ID_REQUIRED',
    TDS_APPLIED: 'TDS_APPLIED'
})